### ISSUE TITLE
creation of AtlasDatabaseUser fail if app.kubernetes.io/version set to higher then operator version. 

### ISSUE THREAD

**Issue by mkyc** [mongodb/mongodb-atlas-kubernetes#1186]
I have 

```yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasDatabaseUser
metadata:
  name: {{ include "lalala.name" . }}
  labels:
    {{- include "lalala.labels" . | nindent 4 }}
```

resource as part of my helm chart. One of labels is `app.kubernetes.io/version` as defined [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) saying which version of application it is. 

Now it will all work until application gets its version higher than operator version. So i.e.: application reaches version `1.7.1` and I have operator in `1.7.0` installed in cluster. Note that those two version values have nothing to do with each other. That all will fail because of [this](https://github.com/mongodb/mongodb-atlas-kubernetes/blob/58c8356408c2bbb24f8ac9601953bb497f7ba1de/pkg/controller/customresource/customresource.go#L27) annotation is IMO overused. Also due to validation logic (this validation is super cool if my `app.kubernetes.io/version` is `0.0.1-SNAPSHOT-13123123` for eternity) it really does look like bug. 

My personal opinion is that [this line](https://github.com/mongodb/mongodb-atlas-kubernetes/blob/main/pkg/controller/customresource/customresource.go#L27) should be: 

```golang
MinimalOperatorVersion                = "operator.mongodb.com/minimal-version"
```
