### ISSUE TITLE
Define the secret name for the connection string output from the operator

### ISSUE THREAD

**Issue by danielloader** [mongodb/mongodb-atlas-kubernetes#1369]
Hello all, instead of using a predictable naming convention for secrets:

$project-$cluster-$username 

I'd like to be able to nominate the output secret name similar to how crossplane does this.

**Comment by roothorp** [comment]
Hi @danielloader, thanks for the issue! I have raised this feature request internally for consideration for future releases.

Could you elaborate on what this feature would ideally look like? Would you like to be able to define the secret name (and have the Operator create it), or point the Operator to an existing secret and have it populate the fields (which looks to be how Crossplane does it?)

**Comment by danielloader** [comment]
Hey, I'm flexible, I think I'm okay with the fixed field model but just providing the secret name if that's possible.

Ideally I'd _prefer_ to be able to name/map the fields out to the secret, so being able to just export a `connectionStringStandardSrv` field, and rename it to `DB_URL`. 

But I'd be happy with just naming the secret, since my connections are by namespace I'd prefer to just output my secrets to something as benign as "mongodb-credentials" without taking into account the project, cluster or username in the resulting secret name.

**Comment by danielloader** [comment]
Additional example found via Aiven.io - https://aiven.io/docs/tools/kubernetes

``` yaml
apiVersion: aiven.io/v1alpha1
kind: PostgreSQL
metadata:
  name: pg-sample
spec:

  # gets the authentication token from the `aiven-token` secret
  authSecretRef:
    name: aiven-token
    key: token

  # outputs the PostgreSQL connection on the `pg-connection` secret
  connInfoSecretTarget:
    name: pg-connection

  # add your Project name here
  project: <your-project-name>

  # cloud provider and plan of your choice
  # you can check all of the possibilities here https://aiven.io/pricing
  cloudName: google-europe-west1
  plan: startup-4

  # general Aiven configuration
  maintenanceWindowDow: friday
  maintenanceWindowTime: 23:00:00

  # specific PostgreSQL configuration
  userConfig:
    pg_version: '11'
```

With the pertinent part being:

``` yaml
# outputs the PostgreSQL connection on the `pg-connection` secret
connInfoSecretTarget:
  name: pg-connection
```
