### ISSUE TITLE
Autogenerate a secret for AtlasDatabaseUser if none provided

### ISSUE THREAD

**Issue by danielloader** [mongodb/mongodb-atlas-kubernetes#1370]
I'd like for the controller to make a random password at the point of submitting the request, the password itself is not relevant to me as it'll be included in the returned connection string to be consumed by the applications themselves.

**Comment by roothorp** [comment]
Hi @danielloader, thanks for the issue! I have raised this feature request internally for consideration for future releases. Could you elaborate further as to what you would like from this feature, and how this would ideally look for you as a user?

**Comment by danielloader** [comment]
Sure thanks for replying.

## The Problem

So currently we have a custom object for the creation of database users:

``` yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasDatabaseUser
metadata:
 name: my-database-user
 labels:
   app.kubernetes.io/version: 1.6.0
spec:
 roles:
   - roleName: readWriteAnyDatabase
     databaseName: admin
 projectRef:
   name: my-project
 username: theuser
 passwordSecretRef:
   name: the-user-password
```

And currently you need to provide the source of the password for the username by means of a password key, in a secret:

```yaml
 passwordSecretRef:
   name: the-user-password
```

While it's great you can provide your own (and the API REST call itself needs you to provide a password for the JSON payload), I'd like to have the option to either create and populate a random secret to the nominated reference if it's missing, or skip this skip all together optionally - and create the password inside of the operator.

The secret is still visible in the resulting connection secret that the operator outputs, but as a moving part I don't need to reference it any other way, nor set it or know about it, my applications use the connection string in the resulting output secret.

## My Current Solution

It's more of a thinking out loud because the alternative is quite clunky for me:

```yaml
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: db-user-password
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  length: 64
  digits: 12
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-user-password
  labels:
    atlas.mongodb.com/type: credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: "0" # once and done
  target:
    name: db-user-password
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: db-user-password
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasDatabaseUser
metadata:
  name: db-user
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  databaseName: "admin"
  roles:
    - roleName: "readWrite"
      databaseName: "example"
  projectRef:
    name: default
    namespace: atlas-operator
  username: db-user
  passwordSecretRef:
    name: db-user-password
  scopes:
    - type: CLUSTER
      name: default
```

As shown I need to have: 
- External secrets operator (which is fine, I use it elsewhere in the cluster, including to get the Atlas API key from AWS Secrets manager) 
- A password generator object
- An external secret that references it and generates this random password and stores it in a secret for the AtlasDatabaseUser to pick up.
- Then finally the AtlasDatabaseUser object references it via the `.spec.passwordSecretRef.name` field.

## Summary

This currently works but it's a lot of moving parts to keep an eye on, more so when you have many microservices, one user per service, all connecting to the same cluster, in many namespaces.

My preference would be the operator just creating the secret if it's missing then self referencing it automatically. 

My second preference would be if it's not included at all then the operator seeds a password at creation time and stores it in the output connection secret reference, possibly even self referencing it in reconciliation loops and updates to the upstream API.
