### ISSUE TITLE
AtlasDatabaseUser - message - unable to list: test because of unknown namespace for the cache

### ISSUE THREAD

**Issue by qtranton** [mongodb/mongodb-atlas-kubernetes#1515]
Have a version of operator 1.7.1 and decide to upgrade to the latest in cluster. 
Create local env 
 
1.  k8s - by docker desktop v 1.25.4
2. operator v1.7.1 
3.  Add AtlasDeployment and AtlasDatabaseUser 
4.  Upgrade to v2.2.0 ( helm upgrade crd then upgrade operator ) 
5.  Fix AtlasDeployment 
6. Check logs of operator get error aka 

```{"level":"INFO","time":"2024-04-16T12:12:14.543Z","msg":"Status update","atlasdatabaseuser":"test/operator-upgrade-test","lastCondition":{"type":"DatabaseUserReady","status":"False","lastTransitionTime":null,"reason":"DatabaseUserStaleConnectionSecrets","message":"unable to list: test because of unknown namespace for the cache"}}```

**What did you expect?**
After all step operator just should work as expected

**What happened instead?**
AtlasDatabaseUser status always in False state 

**Operator Information**
 - 1.7.1 -> 2.2.0
 
**Kubernetes Cluster Information**
 - Docker Desktop
 - 1.25.4

**Additional context**
Try to figure out why AtlasDatabaseUser CRD failed. 
It's created proper secrets and creates users in AtlasUI but CRD itself always in Ready - False state 

`status:
    conditions:
    - lastTransitionTime: "2024-04-16T12:03:17Z"
      status: "False"
      type: Ready
    - lastTransitionTime: "2024-04-16T11:44:08Z"
      status: "True"
      type: ResourceVersionIsValid
    - lastTransitionTime: "2024-04-16T11:44:08Z"
      status: "True"
      type: ValidationSucceeded
    - lastTransitionTime: "2024-04-16T12:03:18Z"
      message: 'unable to list: test because of unknown namespace for the cache'
      reason: DatabaseUserStaleConnectionSecrets
      status: "False"
      type: DatabaseUserReady`

If possible, please include:

`{"level":"DEBUG","time":"2024-04-16T12:17:12.709Z","msg":"Ensured connection Secret up-to-date","atlasdatabaseuser":"test/operator-upgrade-test","secretname":"HIDDEN"}
{"level":"INFO","time":"2024-04-16T12:17:12.709Z","msg":"Status update","atlasdatabaseuser":"test/operator-upgrade-test-","lastCondition":{"type":"DatabaseUserReady","status":"False","lastTransitionTime":null,"reason":"DatabaseUserStaleConnectionSecrets","message":"unable to list: test because of unknown namespace for the cache"}}
`

**Comment by josvazg** [comment]
Thanks for reporting this issue @qtranton !

Could you give us a minimum YAML sample we could use to reproduce the issue?
Does not need to be your original complete setup, just the definitions that reproduce the same failure.

**Comment by qtranton** [comment]
Sure, i have cleanup i guess my yaml here 
```
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: operator-upgrade
    atlas.mongodb.com/type: credentials
    env: dev
  name: operator-upgrade-test
  namespace: test
stringData:
  password: testpassword


---
# Source: app-resources/templates/mongodb_atlas.yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasBackupPolicy
metadata:
  name: operator-upgrade-test
  namespace: test
  annotations:
    mongodb.com/atlas-resource-policy: "keep"
spec:
  items: 
    - frequencyInterval: 12
      frequencyType: hourly
      retentionUnit: days
      retentionValue: 1
    - frequencyInterval: 1
      frequencyType: daily
      retentionUnit: days
      retentionValue: 7
    - frequencyInterval: 6
      frequencyType: weekly
      retentionUnit: weeks
      retentionValue: 1
    - frequencyInterval: 40
      frequencyType: monthly
      retentionUnit: months
      retentionValue: 1
---
# Source: app-resources/templates/mongodb_atlas.yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasBackupSchedule
metadata:
  name: operator-upgrade-test
  namespace: test
  annotations:
    mongodb.com/atlas-resource-policy: "keep"
spec:
  autoExportEnabled: false
  referenceHourOfDay: 21
  referenceMinuteOfHour: 2
  policy:
    name: operator-upgrade-test
    namespace: test
---
# Source: app-resources/templates/mongodb_atlas.yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasDatabaseUser
metadata:
  name: operator-upgrade-test
  labels:
    app: "operator-upgrade"
    env: dev
  #   mongodb.com/atlas-resource-policy: "keep"
spec:
  roles:
  - roleName: readWrite
    databaseName: Application
  scopes:
  - type: CLUSTER
    name: operator-upgrade-test
  projectRef:
    name: project-name
    namespace: mongodb-operator
  username: operator-upgrade-test
  databaseName: admin
  passwordSecretRef:
    name: "operator-upgrade-test"

---
# Source: app-resources/templates/mongodb_atlas.yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: operator-upgrade-test
  namespace: test
  labels:
    app: "operator-upgrade"
    env: dev
  # annotations:
  #   mongodb.com/atlas-resource-policy: "keep"
spec:
  backupRef:
    name: operator-upgrade-test
    namespace: test
  projectRef:
    name: project-name
    namespace: mongodb-operator
  advancedDeploymentSpec:
    mongoDBMajorVersion: "6.0"
    clusterType: REPLICASET
    backupEnabled: true
    pitEnabled: false
    name: operator-upgrade-test
    replicationSpecs:
      - regionConfigs:
        - electableSpecs:
              instanceSize: M10
              nodeCount: 3
          providerName: GCP
          backingProviderName: GCP
          regionName: "EASTERN_US"
          # Priority description https://www.mongodb.com/docs/atlas/reference/atlas-operator/atlasdeployment-custom-resource/#mongodb-setting-spec.advancedDeploymentSpec.replicationSpecs.regionConfigs.priority
          priority: 7
          autoScaling:
            compute:
              enabled: false
```
