### ISSUE TITLE
AtlasDatabaseUser creation fails with internal server error

### ISSUE THREAD

**Issue by vmanikes** [mongodb/mongodb-atlas-kubernetes#1962]
**What did you do to encounter the bug?**
Trying to create a database user as below and it fails with internal server error
```
apiVersion: atlas.mongodb.com/v1
kind: AtlasDatabaseUser
metadata:

  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: data-vault-0.1.0
    mongodb.com/atlas-resource-policy: keep
    mongodb.com/atlas-resource-version: 2.5.0
  name: data-vault-user
  namespace: data-vault
spec:
  awsIamType: ROLE
  databaseName: \$external
  oidcAuthType: NONE
  projectRef:
    name: dev-project
    namespace: infra
  roles:
  - databaseName: admin
    roleName: data-vault
  scopes:
  - name: data-vault
    type: CLUSTER
  username: arn:aws:iam::00000000:role/data-vault
  x509Type: NONE
```

**What did you expect?**
A Database user to be created using the provided IAM role

**What happened instead?**
```
AtlasDatabaseUser  https://cloud.mongodb.com/api/atlas/v2/groups/{projectid}/databaseUsers POST: HTTP 500 Internal Server Error (Error code: "UNEXPECTED_ERROR") Detail: Unexpected error. Reason: Internal Server Error. Params: [
```

**Operator Information**
 - 2.5.0
