### ISSUE TITLE
AtlasDeployment stuck in deployment is updating state

### ISSUE THREAD

**Issue by vmanikes** [mongodb/mongodb-atlas-kubernetes#2106]
**What did you do to encounter the bug?**
I have a deployment with autoscaling enabled
```
            autoScaling:
              compute:
                enabled: true
                maxInstanceSize: M20
                minInstanceSize: M10
                scaleDownEnabled: true
              diskGB:
                enabled: true
```
Now when I change `scaleDownEnabled: false`, the deployment is stuck in updating state
```
NAME         READY   ATLAS STATE   MONGODB VERSION
data-vault   False   UPDATING      8.0.4
```

And when I describe
```
Events:
  Type    Reason              Age                     From             Message
  ----    ------              ----                    ----             -------
  Normal  DeploymentUpdating  4m47s (x3600 over 32d)  AtlasDeployment  deployment is updating
```

**What did you expect?**
Deployment should have been updated successfully

**What happened instead?**
Deployment is stuck in a loop

**Operator Information**
 - 2.6.0
