### ISSUE TITLE
Add a team in a project CR

### ISSUE THREAD

**Issue by cebidhem** [mongodb/mongodb-atlas-kubernetes#212]
Hi there,

At the moment, we can create projects, clusters and db users thanks to the operator.

At project creation, the Atlas user to whom belongs the API key set in the secret is automatically added to the project. 
However, the addition of a team or multiple users within the project creation process could be useful, actually particurarly for the team by adding the team id and its associated permissions as project properties.

This would avoid the need to do it manually through the UI or API calls.

It could be something like
```
spec:
  name: Test project
  teams:
  - teamId: 125067d9afe5fe909d3f1b27
    roleNames: 
    - GROUP_OWNER
    - GROUP_DATA_ACCESS_READ_WRITE
```

What do you think ?
