### ISSUE TITLE
Creating clusters on existing projects

### ISSUE THREAD

**Issue by jacobborella** [mongodb/mongodb-atlas-kubernetes#218]
I'm a member of an organization, where I have only read access. I have been assigned a project within the organization. I'm the administrtor of this project.
With the current capabilities of the Atlas Operator, I can't create a cluster, because it requires me to create a new project. E.g.

```
cat <<EOF | kubectl apply -f -
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: my-project
spec:
  name: Test Atlas Operator Project
  projectIpAccessList:
    - ipAddress: "192.0.2.15"
      comment: "IP address for Application Server A"
    - ipAddress: "203.0.113.0/24"
      comment: "CIDR block for Application Server B - D"
EOF
```

fails with
```
2021-04-26T10:45:03.965Z	INFO	controllers.AtlasProject	Status update	{"atlasproject": "default/mdb-atlas", "lastCondition": {"type":"ProjectReady","status":"False","lastTransitionTime":null,"reason":"ProjectNotCreatedInAtlas","message":"POST https://cloud.mongodb.com/api/atlas/v1.0/groups: 401 (request \"NOT_ORG_GROUP_CREATOR\") The currently logged in user does not have the group creator role in organization <org id>."}}
```
It would be nice with a way to point to my current project, so I can run clusters there.
