### ISSUE TITLE
Operator Dry-run yaml example is incorrect

### ISSUE THREAD

**Issue by RafaelBroseghini** [mongodb/mongodb-atlas-kubernetes#2181]
**What did you do to encounter the bug?**
`kubectl apply` yaml example at: https://www.mongodb.com/docs/atlas/operator/upcoming/ak8so-dry-run/#procedure is incorrect. I couldn't find where to update the docs so I opened the issue.

Containers section is malformed (a lot of properties inside `env` when they should be at the same level). `quay.io` image doesn't exist?

**What did you expect?**
Apply the yaml and cleanly create a Job object

**What happened instead?**
`Error from server (BadRequest): error when creating "local/dry-run.yaml": Job in version "v1" cannot be handled as a Job: json: cannot unmarshal string into Go struct field PodSpec.spec.template.spec.containers of type v1.Container`

**Operator Information**
 - 2.8.0

**Additional context**
Here's my working yaml:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: ako-dry-run
  namespace: mongodb-atlas-system
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: ako-dry-run
        args:
        - --atlas-domain=https://cloud.mongodb.com/
        - --log-level=info
        - --log-encoder=json
        - --dry-run
        command:
        - /manager
        env:
        - name: OPERATOR_POD_NAME
          value: ako-dry-run
        - name: OPERATOR_NAMESPACE
          value: mongodb-atlas-system
        - name: WATCH_NAMESPACE
          value: mongodb-atlas-system
        - name: JOB_NAME
          value: ako-dry-run
        image: mongodb/mongodb-atlas-kubernetes-operator:2.8.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Never
      serviceAccountName: mongodb-atlas-operator

```
