### ISSUE TITLE
AtlasProject Integration stuck in infinite loop

### ISSUE THREAD

**Issue by RafaelBroseghini** [mongodb/mongodb-atlas-kubernetes#2235]
**What did you do to encounter the bug?**
Applying a project with an integration ends up resetting the integration every 10seconds.

Example:

```
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: test
  namespace: test
spec:
  name: test
  connectionSecretRef:
    name: mongodb-atlas-operator-api-key
    namespace: mongodb-atlas-system
  integrations:
  - apiKeyRef:
      name: mongodb-atlas-operator-datadog-api-key
      namespace: mongodb-atlas-system
    region: US
    type: DATADOG
```

**What did you expect?**
Integration gets set up once. Or at least not infinitely.

**What happened instead?**

Integration gets reconfigured in an infinite loop every 10seconds.

**Screenshots**

![Image](https://github.com/user-attachments/assets/b8eb0593-b195-4d6d-8249-de0a6b0ca019)

**Operator Information**
 - Operator Version: 2.8.0

**Additional context**

Problem is likely coming from: 

https://github.com/mongodb/mongodb-atlas-kubernetes/blob/54091dbf436df1418082438b2074f9401aa9dbd5/internal/controller/atlasproject/integrations.go#L48

as both the atlas integration and the spec integration are being evaluted. The comparison is just taking in consideration the integration as an identifier  which will always return true if the integration exists. It also mentions that function is deprecated, so I'm not sure if it's being intended to use.

We find ourselves in a situation where we can't remove the integration from the spec because it will remove from atlas and keeping it will cause the integration to get reconfigured every 10seconds. Our only option is to skip reconciliation via annotation. This would block integration with other project resources such as atlas teams, since we need those to be continuously running.
