### ISSUE TITLE
Datadog Project Alert Configuration Deletes and Creates all alerts configurations on every reconcile

### ISSUE THREAD

**Issue by RafaelBroseghini** [mongodb/mongodb-atlas-kubernetes#2241]
**What did you do to encounter the bug?**

Example project:

```yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
 name: test-project
 namespace: mongodb-atlas-system
spec:
  connectionSecretRef:
    name: mongodb-atlas-operator-api-key
    namespace: mongodb-atlas-system
  name: test-project
  alertConfigurationSyncEnabled: true
  withDefaultAlertsSettings: false
  integrations:
  - apiKeyRef:
      name: mongodb-atlas-operator-api-key
      namespace: mongodb-atlas-system
    region: US
    type: DATADOG
  alertConfigurations:
    - eventTypeName: "JOINED_GROUP"
      enabled: true
      notifications:
      -  delayMin: 0
         intervalMin: 60
         typeName: "DATADOG"
         datadogRegion: "US"
         datadogAPIKeyRef:
          name: mongodb-atlas-operator-api-key
          namespace: mongodb-atlas-system

```

Specifying a project alert configuration based on a datadog integration always fails the spec versus in atlas notifications check at: https://github.com/mongodb/mongodb-atlas-kubernetes/blob/36bbd428eda5c13a7aa8c94ed2de305d89ac5f8a/api/v1/alert_configurations.go#L287-L290

as the apikey comes back redacted. This causes all alerts to be deleted and recreated. We had planned on specifying 30+ alerts through this option in the spec but the bug pollutes the project activity feed making it unusable and harder to identify actual issues.

**What did you expect?**

Datadog alert notifications don't get deleted and recreated on every reconcile.

**What happened instead?**
`{"level":"INFO","time":"2025-03-31T14:17:04.171-0500","msg":"Alert configuration 67eaea299c77db7ecebfcc28 deleted.","atlasproject":"mongodb-atlas-system/test-project"}`

**Screenshots**

![Image](https://github.com/user-attachments/assets/78f834b8-5d94-4c9b-bc02-252e8ecb6ad1)

**Operator Information**
 - 2.8.0

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods
