### ISSUE TITLE
[Bug]: Cannot whitelist IPs using CRD

### ISSUE THREAD

**Issue by dspv** [mongodb/mongodb-atlas-kubernetes#2286]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### AKO Version

v2.8.0

### Distribution

Kubernetes

### Kubernetes Version

v1.32.1

## Problem
Currently, MongoDB Atlas Operator doesn't support managing IP Access Lists through Kubernetes manifests. This forces users to manually configure IP whitelists through the MongoDB Atlas UI or API, breaking the Infrastructure as Code (IaC) principle.

## Proposed Solution
Add IP Access List management to the AtlasProject CRD with the following structure:

```yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: my-project
spec:
  name: my-project
  ipAccessList:
    - ipAddress: "192.168.0.0/24"
      comment: "Office Network"
    - ipAddress: "10.0.0.0/8"
      comment: "VPN Network"
```

## Benefits
- Enables full IaC for MongoDB Atlas configuration
- Improves security by making IP whitelist management part of the deployment process
- Reduces manual configuration steps
- Makes it easier to manage IP whitelists across different environments

## Implementation Details
The operator should:
1. Create/update/delete IP Access List entries when the AtlasProject resource is created/updated/deleted
2. Support both CIDR notation and individual IP addresses
3. Support comments for each entry
4. Handle validation of IP addresses and CIDR notation
5. Provide status updates about the IP Access List configuration

## Additional Context
This is particularly important for:
- Multi-environment deployments
- CI/CD pipelines
- Security compliance requirements
- Team collaboration

### Custom Resources to reproduce the issue

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: atlas-k8s-operator-sa
  namespace: qa1
---
apiVersion: v1
kind: Secret
metadata:
  name: atlas-db-password
  namespace: qa1
  labels:
    atlas.mongodb.com/type: credentials
type: Opaque
data:
  password: d2VtYXRjaHBhc3M=
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-atlas-operator-role
  namespace: qa1
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-atlas-operator-rolebinding
  namespace: qa1
subjects:
- kind: ServiceAccount
  name: mongodb-atlas-operator
  namespace: mongodb-atlas-system
roleRef:
  kind: Role
  name: mongodb-atlas-operator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: euw1-dev-green-qa1
  namespace: qa1
spec:
  name: euw1-dev-green-qa1
  privateEndpoints:
    - region: EU_WEST_1
      provider: AWS
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: qa1-cluster
  namespace: qa1
spec:
  projectRef:
    name: euw1-dev-green-qa1
  deploymentSpec:
    name: qa1-cluster
    clusterType: REPLICASET
    replicationSpecs:
      - regionConfigs:
          - regionName: EU_WEST_1
            providerName: AWS
            electableSpecs:
              instanceSize: M10
              nodeCount: 3
            priority: 7
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasDatabaseUser
metadata:
  name: qa1-user
  namespace: qa1
spec:
  projectRef:
    name: euw1-dev-green-qa1
  username: wematch
  passwordSecretRef:
    name: atlas-db-password
  roles:
    - roleName: "readWriteAnyDatabase"
      databaseName: "admin"
    - roleName: "clusterMonitor"
      databaseName: "admin"
```

### Steps To Reproduce

1. Create Atlas project using operator:
```yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: euw1-dev-green-qa1
  namespace: qa1
spec:
  name: euw1-dev-green-qa1
  privateEndpoints:
    - region: EU_WEST_1
      provider: AWS
```

2. Try to add IP whitelist to project via manifest:
```yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: euw1-dev-green-qa1
  namespace: qa1
spec:
  name: euw1-dev-green-qa1
  ipAccessList:
    - ipAddress: "54.247.82.44/32"
      comment: "NAT Gateway IP"
    - ipAddress: "89.107.59.163/32"
      comment: "GoodAccessVPN"
  privateEndpoints:
    - region: EU_WEST_1
      provider: AWS
```

3. Apply manifest:
```bash
kubectl apply -f 2mongodb.yaml
```

4. Get error:
```
The request is invalid: patch: Invalid value: "{\"apiVersion\":\"atlas.mongodb.com/v1\",\"kind\":\"AtlasProject\",\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"atlas.mongodb.com/v1\\\",\\\"kind\\\":\\\"AtlasProject\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"euw1-dev-green-qa1\\\",\\\"namespace\\\":\\\"qa1\\\"},\\\"spec\\\":{\\\"ipAccessList\\\":[{\\\"comment\\\":\\\"NAT Gateway IP\\\",\\\"ipAddress\\\":\\\"54.247.82.44/32\\\"},{\\\"comment\\\":\\\"GoodAccessVPN\\\",\\\"ipAddress\\\":\\\"89.107.59.163/32\\\"}],\\\"name\\\":\\\"euw1-dev-green-qa1\\\",\\\"privateEndpoints\\\":[{\\\"provider\\\":\\\"AWS\\\",\\\"region\\\":\\\"EU_WEST_1\\\"}]}}\\n\",\"mongodb.com/last-applied-configuration\":\"{\\\"maintenanceWindow\\\":{},\\\"name\\\":\\\"euw1-dev-green-qa1\\\",\\\"privateEndpoints\\\":[{\\\"provider\\\":\\\"AWS\\\",\\\"region\\\":\\\"EU_WEST_1\\\"}],\\\"regionUsageRestrictions\\\":\\\"NONE\\\",\\\"withDefaultAlertsSettings\\\":true}\"},\"creationTimestamp\":\"2025-04-21T07:39:58Z\",\"finalizers\":[\"mongodbatlas/finalizer\"],\"generation\":4,\"managedFields\":[{\"apiVersion\":\"atlas.mongodb.com/v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:kubectl.kubernetes.io/last-applied-configuration\":{}}},\"f:spec\":{\".\":{},\"f:name\":{},\"f:privateEndpoints\":{},\"f:regionUsageRestrictions\\\":{},\"f:withDefaultAlertsSettings\":{}}},\"manager\":\"kubectl-client-side-apply\",\"operation\":\"Update\",\"time\":\"2025-04-21T11:54:19Z\"},{\"apiVersion\":\"atlas.mongodb.com/v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\"f:mongodb.com/last-applied-configuration\":{}},\"f:finalizers\":{\".\":{},\"v:\\\"mongodbatlas/finalizer\\\"\":{}}}},\"manager\":\"manager\",\"operation\":\"Update\",\"time\":\"2025-04-22T07:19:17Z\"},{\"apiVersion\":\"atlas.mongodb.com/v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:status\":{\".\":{},\"f:authModes\":{},\"f:conditions\":{},\"f:id\":{},\"f:observedGeneration\":{},\"f:privateEndpoints\":{}}},\"manager\":\"manager\",\"operation\":\"Update\",\"subresource\":\"status\",\"time\":\"2025-04-22T11:19:44Z\"}],\"name\":\"euw1-dev-green-qa1\",\"namespace\":\"qa1\",\"resourceVersion\":\"8393944\",\"uid\":\"eab653ec-908f-43a0-b6eb-92191706a6f6\"},\"spec\":{\"ipAccessList\":[{\"comment\":\"NAT Gateway IP\",\"ipAddress\":\"54.247.82.44/32\"},{\"comment\":\"GoodAccessVPN\",\"ipAddress\":\"89.107.59.163/32\"}],\"name\":\"euw1-dev-green-qa1\",\"privateEndpoints\":[{\"provider\":\"AWS\",\"region\":\"EU_WEST_1\"}],\"regionUsageRestrictions\":\"NONE\",\"withDefaultAlertsSettings\":true},\"status\":{\"authModes\":[\"SCRAM\"],\"conditions\":[{\"lastTransitionTime\":\"2025-04-22T11:19:44Z\",\"status\":\"True\",\"type\":\"Ready\"},{\"lastTransitionTime\":\"2025-04-21T07:39:58Z\",\"status\":\"True\",\"type\":\"ResourceVersionIsValid\"},{\"lastTransitionTime\":\"2025-04-21T11:54:19Z\",\"status\":\"True\",\"type\":\"ValidationSucceeded\"},{\"lastTransitionTime\":\"2025-04-22T07:38:43Z\",\"status\":\"True\",\"type\":\"ProjectReady\"},{\"lastTransitionTime\":\"2025-04-22T07:22:18Z\",\"message\":\"Interface Private Endpoint awaits configuration\",\"status\":\"True\",\"type\":\"PrivateEndpointServiceReady\"}],\"id\":\"680742f10afbe35fcbffa9af\",\"observedGeneration\":4,\"privateEndpoints\":[{\"id\":\"680742f7d64e76229ecdaeb0\",\"provider\":\"AWS\",\"region\":\"EU_WEST_1\",\"serviceName\":\"com.amazonaws.vpce.eu-west-1.vpce-svc-004ed722343fd92c5\",\"serviceResourceId\":\"680742f7d64e76229ecdaeb0\"}]}}": strict decoding error: unknown field "spec.ipAccessList"
```

5. Check that `ipAccessList` field is not supported in CRD:
```bash
kubectl get crd atlasprojects.atlas.mongodb.com -o yaml
```

### Logs

```txt

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
