### ISSUE TITLE
[Bug]: TagSpec Value does not accept spaces

### ISSUE THREAD

**Issue by RafaelBroseghini** [mongodb/mongodb-atlas-kubernetes#2329]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### AKO Version

v2.8.0

### Distribution

Kubernetes

### Kubernetes Version

v1.30.5

### Current Behavior

Adding a tag value with spaces in it fails CRD validation.

It seems like keys are allowed to contain spaces in it and it's supported via the UI. Not sure if it was a mistake or if there's a reason for this.

https://github.com/mongodb/mongodb-atlas-kubernetes/blob/a9ac619a29a42cfb6263983274d4f26c3be21b5d/api/v1/atlasdeployment_types.go#L217-L222

### Custom Resources to reproduce the issue

```yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: my-atlas-cluster
spec:
  projectRef:
    name: my-project
  deploymentSpec:
    clusterType: REPLICASET
    name: tenantCluster
    tags:
    - key: "name"
      value: "john doe"
    replicationSpecs:
      - zoneName: Zone 1
```

### Steps To Reproduce

1. Create AtlasDeployment
2. Check CRD validation error

### Logs

```txt
The AtlasDeployment "my-atlas-cluster" is invalid: spec.deploymentSpec.tags[0].value: Invalid value: "john doe": spec.deploymentSpec.tags[0].value in body should match '^[a-zA-Z0-9][a-zA-Z0-9@_.+`;`-]*$'
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
