### ISSUE TITLE
Default "backingProviderName" Conflicts with Provisioning of Dedicated Cluster

### ISSUE THREAD

**Issue by alex-tw-lam** [mongodb/mongodb-atlas-kubernetes#233]
Default values.yaml: 
```
mongodb:
  providerSettings:
    instanceSizeName: M2
    providerName: TENANT
    backingProviderName: AWS
    regionName: US_EAST_1

```

values.yaml used during the installation:
```
mongodb:
  providerSettings:
    providerName: AZURE
    instanceSizeName: M10
    regionName: ASIA_EAST
    diskTypeName: P4
  providerBackupEnabled: true
  labels:
    - key: cost_center
      value: '180521'
```

Error messages:
```
  - lastTransitionTime: "2021-05-18T08:08:57Z"
    message: 'PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/60a369248984fe4451779ec9/clusters/atlas-cluster: 400 (request "INVALID_ATTRIBUTE") Invalid attribute backingProviderName specified.'
    reason: ClusterNotUpdatedInAtlas
    status: "False"
    type: ClusterReady
```

Apparently, the "backingProviderName" parameter is blocking the operator app from creating a dedicated cluster. 

Workaround: 
```
1. download the helm chart; 
2. manually mask the "backingProviderName" parameters
3. install the local helm chart
```
