### ISSUE TITLE
API Keys Should be Abstracted Away from Cluster Creation 

### ISSUE THREAD

**Issue by alex-tw-lam** [mongodb/mongodb-atlas-kubernetes#234]
Currently, the API key is provided during cluster creation when using the `mongodb/atlas-cluster` operator. 

```
atlas:
  orgId: ***
  publicApiKey: ***
  privateApiKey: ***
  connectionSecretName: ***
```

Ideally, the API key should be pre-configured on the operator app, e.g. when installing `mongodb/atlas-operator`, instead of having to provide each time during there's a new cluster creation.
