### ISSUE TITLE
non-root Security Contexts Blocking Installation of mongodb/mongodb-atlas-operator Helm Chart

### ISSUE THREAD

**Issue by alex-tw-lam** [mongodb/mongodb-atlas-kubernetes#236]
Encountered the following error when using the helm's default security context: 
`Warning  Failed     2m56s (x5 over 4m23s)  kubelet            Error: failed to start container "kube-rbac-proxy": Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: chdir to cwd ("/home/nonroot") set in config.json failed: permission denied: unknown
`

Tested under Kubernetes version `v1.19.11`

Workaround: 
```
podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
securityContext:
  allowPrivilegeEscalation: true
```
