### ISSUE TITLE
Support of scopes for AtlasDatabaseUser is broken in the Helm chart

### ISSUE THREAD

**Issue by denist-huma** [mongodb/mongodb-atlas-kubernetes#262]
```yaml
mongodb-atlas-operator:
  enabled: true

# Please provide Atlas API credentials and Organization
atlas:
  orgId: "<Atlas Organization ID>"
  publicApiKey: "<Atlas_api_public_key>"
  privateApiKey: "<Atlas_api_private_key>"

  connectionSecretName: ""

project:
  name: my-project
  atlasProjectName: "Test Project"
  # fullnameOverride: ""

  projectIpAccessList:
    - ipAddress: "192.0.2.15"
      comment: "IP address for Application Server A"
    - ipAddress: "203.0.113.0/24"
      comment: "CIDR block for Application Server B - D"

mongodb:
  providerSettings:
    instanceSizeName: M2
    providerName: TENANT
    backingProviderName: AWS
    regionName: US_EAST_1

# Optional section. for more information visit
# https://docs.atlas.mongodb.com/reference/api/clusters-create-one/
# #
#   autoScaling:
#     autoIndexingEnabled: false
#     compute:
#       enabled: false
#       maxInstanceSize: 'M40'
#       minInstanceSize: 'M10'
#       scaleDownEnabled: false
#     diskGBEnabled: false
#   biConnector:
#     enabled: false
#     readPreference: 'primary'
#   clusterType: 'REPLICASET'
#   diskSizeGB: '50'
#   encryptionAtRestProvider: 'AWS'
#   labels:
#   mongoDBMajorVersion: '4.4'
#   numShards: 2
#   paused: false
#   pitEnabled: false
#   providerBackupEnabled: false
#   replicationSpecs:
users:
  - username: admin-user
    databaseName: admin
    password: "%SomeLong%password$foradmin"
    roles:
      - databaseName: admin
        roleName: atlasAdmin
    # deleteAfterDate:
    # labels:
    scopes:
      - name: atlas-operator-demo-cluster-atlas-cluster
        type: CLUSTER
```

```sh
COMBINED OUTPUT:
  Error: Failed to render chart: exit status 1: Error: YAML parse error on atlas-cluster/templates/atlas-mongodb-user.yaml: error converting YAML to JSON: yaml: line 21: did not find expected ',' or ']'
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error
```
