### ISSUE TITLE
Support for cross-region cluster

### ISSUE THREAD

**Issue by alex-tw-lam** [mongodb/mongodb-atlas-kubernetes#279]
Disaster recovery is a capability required by many enterprises. we want to be able to create clusters within the atlas operator with DR enabled by default.

**Comment by leo-ri** [comment]
Hi @alex-tw-lam 
Cross-region cluster is supported right now, here's a sample:

```
apiVersion: atlas.mongodb.com/v1
kind: AtlasCluster
metadata:
  name: atlascluster-multiregion-azure
spec:
  name: cluster-multiregion-azure
  projectRef:
    name: my-project
  providerBackupEnabled: true
  clusterType: REPLICASET
  providerSettings:
    instanceSizeName: M10
    providerName: AZURE
  replicationSpecs:
  - numShards: 1
    zoneName: Europe
    regionsConfig:
      NORWAY_EAST:
        analyticsNodes: 0
        electableNodes: 1
        priority: 6
        readOnlyNodes: 0
      GERMANY_NORTH:
        analyticsNodes: 0
        electableNodes: 1
        priority: 7
        readOnlyNodes: 0
```

if there are any issues and it is not working for you, please, send logs, and yours configs
