### ISSUE TITLE
Disable autoScaling doesn't work

### ISSUE THREAD

**Issue by tetianakravchenko** [mongodb/mongodb-atlas-kubernetes#311]
Hello,

I am trying to disable autoScaling:
previous configuration:
```
apiVersion: atlas.mongodb.com/v1
kind: AtlasCluster
metadata:
  name: test-test-cluster
  labels:
    helm.sh/chart: atlas-clusters-0.0.1
    app.kubernetes.io/name: atlas-clusters
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.5.0"
    app.kubernetes.io/managed-by: Helm
  namespace: mongodb-operator
  annotations:
    mongodb.com/atlas-resource-policy: keep
spec:
  name: test-cluster
  projectRef:
    name: test1
  autoScaling:
    compute:
      enabled: true
      scaleDownEnabled: true
  diskSizeGB: 10
  mongoDBMajorVersion: "4.4"
  numShards: 1
  pitEnabled: false
  providerBackupEnabled: true
  providerSettings:
    instanceSizeName: M10
    providerName: GCP
    regionName: WESTERN_EUROPE
    autoScaling:
      compute:
        maxInstanceSize: M30
        minInstanceSize: M10
```

```
apiVersion: atlas.mongodb.com/v1
kind: AtlasCluster
metadata:
  name: test-test-cluster
  labels:
    helm.sh/chart: atlas-clusters-0.0.1
    app.kubernetes.io/name: atlas-clusters
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.5.0"
    app.kubernetes.io/managed-by: Helm
  namespace: mongodb-operator
  annotations:
    mongodb.com/atlas-resource-policy: keep
spec:
  name: test-cluster
  projectRef:
    name: test1
  autoScaling:
    compute:
      enabled: false
      scaleDownEnabled: false
  diskSizeGB: 10
  mongoDBMajorVersion: "4.4"
  numShards: 1
  pitEnabled: false
  providerBackupEnabled: true
  providerSettings:
    instanceSizeName: M10
    providerName: GCP
    regionName: WESTERN_EUROPE
```

but I am getting next message:
```
2021-08-19T08:54:45.379Z	INFO	controllers.AtlasCluster	Status update	{"atlascluster": "mongodb-operator/test-test-cluster", "lastCondition": {"type":"ClusterReady","status":"False","lastTransitionTime":null,"reason":"ClusterNotUpdatedInAtlas","message":"PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/PROJECT_ID/clusters/test-cluster: 400 (request \"COMPUTE_AUTO_SCALING_MIN_INSTANCE_SIZE_INVALID_FOR_DISABLED\") Compute auto-scaling min instance size must be unset when scale down is disabled."}}
```

What is an expected procedure to disable autoscaling?
