### ISSUE TITLE
Storage autoScaling with diskSizeGB

### ISSUE THREAD

**Issue by tetianakravchenko** [mongodb/mongodb-atlas-kubernetes#316]
By default `autoScaling.diskGBEnabled ` is [enabled](https://github.com/mongodb/mongodb-atlas-kubernetes/blob/main/deploy/crds/atlas.mongodb.com_atlasclusters.yaml#L73-L76)

I've tried to create cluster with `instanceSizeName: M10`, for this instanceSize suggested `diskSizeGB` is 10 GB, I want to create cluster with bigger disk:
```
providerSettings:
  instanceSizeName: M10
  providerName: GCP
  regionName: WESTERN_EUROPE
diskSizeGB: 12
```
Then I've resized disk manually to 14GB (I didn't have enough data to have autoScaling to trigger disk resize, but I think this scenario is comparable).
With the next changes of `AtlasCluster` CR (added `providerBackupEnabled: false`, but the actual change is not important here):
```
providerSettings:
  instanceSizeName: M10
  providerName: GCP
  regionName: WESTERN_EUROPE
diskSizeGB: 12
providerBackupEnabled: false 
```
And this triggers the disk to be downscaled to `14GB -> 12GB` as defined in spec
How `diskSizeGB` suppose to work with `autoScaling.diskGBEnabled`? Is it expected behavior? I would expect that `diskSizeGB` would be skipped after initial provisioning if `autoScaling.diskGBEnabled` is enabled
