### ISSUE TITLE
AtlasCluster CRD is not aligned with API

### ISSUE THREAD

**Issue by tetianakravchenko** [mongodb/mongodb-atlas-kubernetes#318]
In `AtlasCluster` custom resource definition is defined that property `autoScaling` support next `compute` properties:
```
autoScaling:
  compute:
    enabled: ...
    maxInstanceSize: ...
    minInstanceSize: ...
    scaleDownEnabled: ...
```
https://github.com/mongodb/mongodb-atlas-kubernetes/blob/main/deploy/crds/atlas.mongodb.com_atlasclusters.yaml#L48-L71 
The same set of properties is defined for `proverSettings.autoScaling`:
https://github.com/mongodb/mongodb-atlas-kubernetes/blob/main/deploy/crds/atlas.mongodb.com_atlasclusters.yaml#L186-L211

If I try to set:
```
autoScaling:
  compute:
    enabled: true
    maxInstanceSize: M80
    minInstanceSize: M50
    scaleDownEnabled: true
```
it fails with error:
```
400 (request \"INVALID_ATTRIBUTE\") Invalid attribute minInstanceSize specified."}
```
full output:
```
  	AutoScaling: &mongodbatlas.AutoScaling{
  		AutoIndexingEnabled: &false,
  		Compute: &mongodbatlas.Compute{
- 			Enabled:          &false,
+ 			Enabled:          &true,
- 			ScaleDownEnabled: &false,
+ 			ScaleDownEnabled: &true,
- 			MinInstanceSize:  "",
+ 			MinInstanceSize:  "M10",
- 			MaxInstanceSize:  "",
+ 			MaxInstanceSize:  "M30",
  		},
  		DiskGBEnabled: &true,
  	},
  	BackupEnabled: &false,
  	BiConnector:   &{Enabled: &false, ReadPreference: "secondary"},
  	... // 23 identical fields
  }
	{"atlascluster": "mongodb-operator/test-test-cluster"}
2021-08-26T12:22:17.381Z	DEBUG	controllers.AtlasCluster	HTTP Request (PATCH) https://cloud.mongodb.com/api/atlas/v1.0/groups/XXXXX/clusters/test-cluster [time (ms): 199, status: 400]	{"atlascluster": "mongodb-operator/test-test-cluster"}
2021-08-26T12:22:17.381Z	INFO	controllers.AtlasCluster	Status update	{"atlascluster": "mongodb-operator/test-test-cluster", "lastCondition": {"type":"ClusterReady","status":"False","lastTransitionTime":null,"reason":"ClusterNotUpdatedInAtlas","message":"PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/XXXXXXX/clusters/test-cluster: 400 (request \"INVALID_ATTRIBUTE\") Invalid attribute minInstanceSize specified."}}
```

according to https://docs.atlas.mongodb.com/reference/api/clusters-create-one/ there are no such properties like:
```
autoScaling.compute.maxInstanceSize
autoScaling.compute.minInstanceSize
providerSettings.autoScaling.compute.enabled
providerSettings.autoScaling.compute.scaleDownEnabled
```
that are defined in CRD. Are there any reason for that?

It is misleading that in CRD is defined that those settings should work, but in reality, the next configuration works:
```
providerSettings:
  autoScaling:
    compute:
      maxInstanceSize: M30
      minInstanceSize: M10
autoScaling:
  compute:
    enabled: true
    scaleDownEnabled: true
```
