### ISSUE TITLE
Unable to change `instanceSize` with `advancedDeploymentSpec`

### ISSUE THREAD

**Issue by sunchill06** [mongodb/mongodb-atlas-kubernetes#649]
**What did you do to encounter the bug?**
Steps to reproduce the behaviour:

Created an `AtlasDeployment` with following spec:
```yaml
kind: AtlasDeployment
metadata:
  name: one     
spec:
  projectRef:
    name: playground-project
  advancedDeploymentSpec:
      clusterType: SHARDED
      name: one
      backupEnabled: true
      diskSizeGB: 10
      mongoDBMajorVersion: "4.4"
      pitEnabled: false
      replicationSpecs:
      - numShards: 1
        regionConfigs:
        - autoScaling:
            compute:
              enabled: true
              maxInstanceSize: M40
              minInstanceSize: M30
              scaleDownEnabled: true
            diskGBEnabled: true
          electableSpecs:
            instanceSize: M30
            nodeCount: 3
          providerName: GCP
          regionName: WESTERN_EUROPE
          priority: 7
```
Update the spec to change the `instanceSize` to `M40`

**What did you expect?**
Expected the Operator to reconcile this and Atlas API to accommodate this request.

**What happened instead?**
Operator logs show following:

```console
{"level":"INFO","time":"2022-08-18T10:13:29.920Z","msg":"-> Starting AtlasDeployment reconciliation","atlasdeployment":"mongodb/one","spec":{"projectRef":{"name":"playground-project","namespace":""},"advancedDeploymentSpec":{"backupEnabled":true,"clusterType":"SHARDED","diskSizeGB":10,"mongoDBMajorVersion":"4.4","name":"one","pitEnabled":false,"replicationSpecs":[{"numShards":1,"regionConfigs":[{"electableSpecs":{"instanceSize":"M40","nodeCount":3},"autoScaling":{"compute":{"enabled":true,"scaleDownEnabled":true,"minInstanceSize":"M30","maxInstanceSize":"M40"}},"priority":7,"providerName":"GCP","regionName":"WESTERN_EUROPE"}]}]},"backupRef":{"name":"","namespace":""}},"status":{"conditions":[{"type":"Ready","status":"False","lastTransitionTime":"2022-08-18T10:13:29Z"},{"type":"ValidationSucceeded","status":"True","lastTransitionTime":"2022-08-18T10:01:06Z"},{"type":"DeploymentReady","status":"True","lastTransitionTime":"2022-08-18T10:12:22Z"}],"observedGeneration":2,"stateName":"IDLE","mongoDBVersion":"4.4.15","connectionStrings":{"standard":"mongodb://one-shard-00-00.dw7cw.mongodb.net:27016,one-shard-00-01.dw7cw.mongodb.net:27016,one-shard-00-02.dw7cw.mongodb.net:27016/?ssl=true&authSource=admin","standardSrv":"mongodb+srv://one.dw7cw.mongodb.net"}}}
{"level":"INFO","time":"2022-08-18T10:13:30.328Z","msg":"Status update","atlasdeployment":"mongodb/one","lastCondition":{"type":"DeploymentReady","status":"False","lastTransitionTime":null,"reason":"DeploymentNotUpdatedInAtlas","message":"PATCH https://cloud.mongodb.com/api/atlas/v1.5/groups/62fb6c0da131bd11a75ec2f9/clusters/one: 400 (request \"BASE_INSTANCE_SIZE_MUST_MATCH\") Electable and read-only nodes must all have the same instance size."}}
```

Next, tried to provide `readOnlySpecs` as well while updating the `instanceSize`. Below is the new spec.
```yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: one     
spec:
  projectRef:
    name: playground-project
  advancedDeploymentSpec:
      clusterType: SHARDED
      name: one
      backupEnabled: true
      diskSizeGB: 10
      mongoDBMajorVersion: "4.4"
      pitEnabled: false
      replicationSpecs:
      - numShards: 1
        regionConfigs:
        - autoScaling:
            compute:
              enabled: true
              maxInstanceSize: M40
              minInstanceSize: M30
              scaleDownEnabled: true
            diskGBEnabled: true
          electableSpecs:
            instanceSize: M40
            nodeCount: 3
          readOnlySpecs:
            instanceSize: M40
          providerName: GCP
          regionName: WESTERN_EUROPE
          priority: 7
```

Observation in Operator logs:
```console
{"level":"INFO","time":"2022-08-18T10:18:43.628Z","msg":"-> Starting AtlasDeployment reconciliation","atlasdeployment":"mongodb/one","spec":{"projectRef":{"name":"playground-project","namespace":""},"advancedDeploymentSpec":{"backupEnabled":true,"clusterType":"SHARDED","diskSizeGB":10,"mongoDBMajorVersion":"4.4","name":"one","pitEnabled":false,"replicationSpecs":[{"numShards":1,"regionConfigs":[{"electableSpecs":{"instanceSize":"M40","nodeCount":3},"readOnlySpecs":{"instanceSize":"M40","nodeCount":0},"autoScaling":{"compute":{"enabled":true,"scaleDownEnabled":true,"minInstanceSize":"M30","maxInstanceSize":"M40"}},"priority":7,"providerName":"GCP","regionName":"WESTERN_EUROPE"}]}]},"backupRef":{"name":"","namespace":""}},"status":{"conditions":[{"type":"Ready","status":"False","lastTransitionTime":"2022-08-18T10:13:29Z"},{"type":"ValidationSucceeded","status":"True","lastTransitionTime":"2022-08-18T10:01:06Z"},{"type":"DeploymentReady","status":"False","lastTransitionTime":"2022-08-18T10:13:30Z","reason":"DeploymentNotUpdatedInAtlas","message":"PATCH https://cloud.mongodb.com/api/atlas/v1.5/groups/62fb6c0da131bd11a75ec2f9/clusters/one: 400 (request \"AUTO_SCALING_NOT_SUPPORTED\") Cannot set auto-scaling. Auto-scaling not supported for asymmetric clusters.."}],"observedGeneration":3,"stateName":"IDLE","mongoDBVersion":"4.4.15","connectionStrings":{"standard":"mongodb://one-shard-00-00.dw7cw.mongodb.net:27016,one-shard-00-01.dw7cw.mongodb.net:27016,one-shard-00-02.dw7cw.mongodb.net:27016/?ssl=true&authSource=admin","standardSrv":"mongodb+srv://one.dw7cw.mongodb.net"}}}

{"level":"INFO","time":"2022-08-18T10:18:44.093Z","msg":"Status update","atlasdeployment":"mongodb/one","lastCondition":{"type":"DeploymentReady","status":"False","lastTransitionTime":null,"reason":"DeploymentNotUpdatedInAtlas","message":"PATCH https://cloud.mongodb.com/api/atlas/v1.5/groups/62fb6c0da131bd11a75ec2f9/clusters/one: 400 (request \"AUTO_SCALING_NOT_SUPPORTED\") Cannot set auto-scaling. Auto-scaling not supported for asymmetric clusters.."}}
```

**Screenshots**
N/A

**Operator Information**
 - Operator Version (1.2.0)

Questions:
1. Are  we supposed to update `instanceSize` with operator (Custom resource spec) when autoScaling is enabled.
2. if yes, why are we supposed to provide `readOnlySpecs` when we don't want them and just have `electableSpecs`.
3. if no, is this behaviour of the operator documented somewhere and do we have any Do's and Don'ts with the operator?

**Comment by fabritsius** [comment]
Hey @sunchill06,

Haven't seen such `asymmetric clusters` error myself. Will try to reproduce and will get back to you.

**Comment by fabritsius** [comment]
Cannot reproduce. Was able to jump back and forth between these two configs without issues:
```
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: one     
spec:
  projectRef:
    name: playground-project
  advancedDeploymentSpec:
      clusterType: SHARDED
      name: one
      backupEnabled: true
      diskSizeGB: 10
      mongoDBMajorVersion: "4.4"
      pitEnabled: false
      replicationSpecs:
      - numShards: 1
        regionConfigs:
        - autoScaling:
            compute:
              enabled: true
              maxInstanceSize: M40
              minInstanceSize: M30
              scaleDownEnabled: true
            diskGB:
              enabled: true
          electableSpecs:
            instanceSize: M30
            nodeCount: 3
          readOnlySpecs:
            instanceSize: M30
            nodeCount: 3
          providerName: GCP
          regionName: WESTERN_EUROPE
          priority: 7
```

```
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: one     
spec:
  projectRef:
    name: playground-project
  advancedDeploymentSpec:
      clusterType: SHARDED
      name: one
      backupEnabled: true
      diskSizeGB: 10
      mongoDBMajorVersion: "4.4"
      pitEnabled: false
      replicationSpecs:
      - numShards: 1
        regionConfigs:
        - autoScaling:
            compute:
              enabled: true
              maxInstanceSize: M40
              minInstanceSize: M30
              scaleDownEnabled: true
            diskGB:
              enabled: true
          electableSpecs:
            instanceSize: M40
            nodeCount: 3
          readOnlySpecs:
            instanceSize: M40
            nodeCount: 3
          providerName: GCP
          regionName: WESTERN_EUROPE
          priority: 7
```

Notable changes are:
- `diskGBEnabled` changed to new form `diskGB.enabled`
- added `nodeCount` to `readOnlySpecs`

Both of these give a different error so are unlikely the cause of your issues.

Please try to update your specs and let me know if the problem persists.
Thanks 🙏
