### ISSUE TITLE
localhost forbid for database datadog sample

### ISSUE THREAD

**Issue by Azaretdodo** [mongodb/mongodb-atlas-kubernetes#653]
**What did you do to encounter the bug?**

```
cat <<EOF | kubectl apply -f -
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
name: my-project
spec:                                     
name: TestAtlasOperatorProjectIntegration3
connectionSecretRef:
name: my-atlas-key
projectIpAccessList:
- ipAddress: "0.0.0.0/1"
comment: "Everyone has access. For the test purpose only."
- ipAddress: "128.0.0.0/1"
comment: "Everyone has access. For the test purpose only."
integrations:
- type: "DATADOG"
apiKeyRef:
name: key-datadog
namespace: key-namespace
region: "FR"
EOF
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**What did you expect?**
A clear and concise description of what you expected to happen. the database datadog should be upload

**What happened instead?**
A clear and concise description of what happened instead : i got an error of firewall

**Screenshots**

**Operator Information**
 - Operator Version : `kubernetes --version
1.0.0
`

**Kubernetes Cluster Information**
 - Distribution ubuntu 22.04 Jammy
 - Version Kubernetes 1.0 and mongodb 6.0
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output : `kubectl describe
error: You must specify the type of resource to describe. Use "kubectl api-resources" for a complete list of supported resources.
kubectl api-resources
NAME   SHORTNAMES   APIVERSION   NAMESPACED   KIND
The connection to the server localhost:8080 was refused - did you specify the right host or port?
` 
 - yaml definitions for your objects how to find this ?
 - log files for the operator and database pods how to find this ?

**Comment by fabritsius** [comment]
Hey @Azaretdodo,

To apply the changes to the cluster you need you need to use `kubectl apply` command like this:
```
cat <<EOF | kubectl apply -f -
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: my-project
spec:
  name: TestAtlasOperatorProjectIntegration3
  projectIpAccessList:
    - ipAddress: "0.0.0.0/1"
      comment: "Everyone has access. For the test purpose only."
    - ipAddress: "128.0.0.0/1"
      comment: "Everyone has access. For the test purpose only."
  integrations:
    - type: "DATADOG"
      apiKeyRef:
        name: the-datadog-key
        namespace: "mongodb-atlas-system"
      region: "US"
EOF
```

Let me know if this won't help. Thanks 🙏
