### ISSUE TITLE
Secret with connection secrets is not created for serverless instance

### ISSUE THREAD

**Issue by ThumNet** [mongodb/mongodb-atlas-kubernetes#791]
**What did you do to encounter the bug?**

Apply the following helm template

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: testing
  labels:
    atlas.mongodb.com/type: "credentials"
type: Opaque
stringData:
  password: "OENkWWcxR3JleVZucGNsU1Z5M3lxSkpjTllBejhVeWM="
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasDatabaseUser
metadata:
  name: atlas-deployment-user-testing
  labels:
    helm.sh/chart: testing-0.0.1_replaced.by.yq.in.pipeline
    app.kubernetes.io/name: testing
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  username: tester
  passwordSecretRef:
    name: tester-secret
  projectRef:
    name: mongodb-atlas-project
    namespace: mongodb-atlas
  roles:
    - databaseName: testdb
      roleName: readWrite
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: atlas-deployment
  labels:
    helm.sh/chart: testing-0.0.1_replaced.by.yq.in.pipeline
    app.kubernetes.io/name: testing
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  projectRef:
    name: mongodb-atlas-project
    namespace: mongodb-atlas
  backupRef:
    name: ''
    namespace: ''
  serverlessSpec:
    name: testdeployment
    providerSettings:
      providerName: AZURE
      regionName: EUROPE_WEST
```

**What did you expect?**
- [OK] AtlasDeployment created in k8s
  - [OK] Deployment created in Atlas Cloud
- [OK] AtlasDatabaseUser created in k8s
  - [OK] User created in Atlas Cloud
- **[NOK]** Secret containing the [connection secrets](https://www.mongodb.com/docs/atlas/reference/atlas-operator/atlasdatabaseuser-custom-resource/#connection-secrets) o be created in k8s

**What happened instead?**
Everything else worked as expected, just the secret containing the connection secrets was not created.

**NOTE**
After trying the same template and changing the `serverlessSpec` to a `deploymentSpec` we see the `secret` getting created.

**Screenshots**

**Operator Information**
 - Operator Version: 1.5.0

**Kubernetes Cluster Information**
 - Distribution
 - Version: 1.24.3
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by Sugar-pack** [comment]
Hi @ThumNet, thanks a lot for raising an issue. In order for the secret to be created, you need an instance, a user, and a connected private endpoint. In the case of a serverless instance, you need to set up the private endpoint in the serverless spec. More details can be found in the documentation: https://www.mongodb.com/docs/atlas/reference/atlas-operator/ak8so-private-link-serverless/

**Comment by sunib** [comment]
Thanks @Sugar-pack: I'm a colleague of @ThumNet and we ran into this issue together.

Just to verify: we got this working with a deploymentSpec, and this works without configuring a private-link. Is this a requirement? The docs say that this is [optional](https://www.mongodb.com/docs/atlas/reference/atlas-operator/atlasdeployment-custom-resource/#mongodb-setting-spec.serverlessSpec.privateEndpoints) if I understand this correctly.

I would like to start without a private-link, as I'm already very happy with all the options.

**Comment by Sugar-pack** [comment]
@sunib, you are right. The secret should be created even without configured private endpoints. In this case, it will contain empty strings in the connectionStringPrivate and connectionStringPrivateSrv fields. Could you please check if connection strings data appeared in the deployment status? The status should looks like this:
```
status:
  conditions:
    - lastTransitionTime: '2022-12-09T05:30:02Z'
      status: 'True'
      type: Ready
    - lastTransitionTime: '2022-12-08T07:28:42Z'
      status: 'True'
      type: ValidationSucceeded
    - lastTransitionTime: '2022-12-09T05:29:54Z'
      status: 'True'
      type: DeploymentReady
  connectionStrings:
    standardSrv: mongodb+srv://some_conn_string
  mongoDBVersion: 6.2.0-rc2
  observedGeneration: 4
  stateName: IDLE
```

**Comment by sunib** [comment]
I think it was in status: but I will retry today to confirm this (all resources are now deleted).

The operator is installed by helm (https://mongodb.github.io/helm-charts/mongodb-atlas-operator:1.5.0). We use Argo to deploy it and no values are overriden.

To be complete, the application manifest from Argo that does this:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-atlas-operator
  namespace: argocd
spec:
  destination:
    namespace: mongodb-atlas
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://mongodb.github.io/helm-charts
    targetRevision: '1.5.0'
    chart: mongodb-atlas-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
