### ISSUE TITLE
Serverless AtlasDeployment on GCP fails

### ISSUE THREAD

**Issue by pabloromeo** [mongodb/mongodb-atlas-kubernetes#821]
**What did you do to encounter the bug?**
Attempted to create a Serverless Deployment on GCP using:
```
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: some-name
spec:
  projectRef:
    name: some-name
  serverlessSpec:
    name: some-name
    providerSettings:
      providerName: GCP
      regionName: CENTRAL_US
```
The Database is in fact created correctly in Atlas without issues, however, the Operator fails to finish the creation process, showing the following status:
```
Status:
  Conditions:
    Last Transition Time:  2023-01-03T03:13:31Z
    Status:                False
    Type:                  Ready
    Last Transition Time:  2023-01-03T03:13:31Z
    Status:                True
    Type:                  ValidationSucceeded
    Last Transition Time:  2023-01-03T03:13:32Z
    Message:               serverless private endpoints are only supported for AWS and Azure
    Reason:                InternalError
    Status:                False
    Type:                  DeploymentReady
  Observed Generation:     2
  State Name:              IDLE
```

**What did you expect?**
I expected to be able to provision a Serverless Deployment on GCP without using private endpoints

**What happened instead?**
The Operator just continues to loop on the Internal Error, when the DB has already been deployed and the Secret with the connection string should have been created (which hasn't).

**Screenshots**
The Deployment is actually created, but for some reason the Operator thinks I attempted to use private endpoints.
<img width="512" alt="image" src="https://user-images.githubusercontent.com/41338020/210297243-c94f861d-bd7c-46a9-870e-9f24c70d79bc.png">

**Operator Information**
 - v1.5.1

**Kubernetes Cluster Information**
 - GKE
 - 1.24.7-gke.900

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods
