### ISSUE TITLE
Operator does not reconcile notifications (Slack in my case)

### ISSUE THREAD

**Issue by zelig81** [mongodb/mongodb-atlas-kubernetes#863]
**What did you do to encounter the bug?**
- add manually integration of Slack (I added both on Organizational level and on Project level)
- add notification via Slack in alert of a Project
- generate via `atlas kubernetes generate ...` a Project k8s manifest
- apply it
- remove manually the first notification via Slack in the alert of the Project
- add second notification only via k8s manifest

**What did you expect?**
- get the first notification back via reconcile loop of Operator
- get the second notification back via reconcile loop of operator
- the best outcome IMHO - it should be done automatically without AtlasProject k8s manifest to be changed (for reconcilation of manual changes)

**What happened instead?**
A clear and concise description of what happened instead
- the first notification did not get back
- the second notification was not added

**Operator Information**
 - Operator Version v1.5.1

**Kubernetes Cluster Information**
 - Distribution GKE
 - Version 1.24
 - Image Registry location: default

**Additional context**

<details><summary>AtlasProject k8s manifest</summary>

```yaml
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  creationTimestamp: null
  name: poc_project
  namespace: atlas
spec:
  alertConfigurations:
  - enabled: true
    eventTypeName: REPLICATION_OPLOG_WINDOW_RUNNING_OUT
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    - apiToken: '*************************************************************************1234'
      channelName: ilya-test-channel
      delayMin: 0
      intervalMin: 60
      typeName: SLACK
    threshold:
      operator: LESS_THAN
      threshold: "1.000000"
      units: HOURS
  - enabled: true
    eventTypeName: NO_PRIMARY
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 15
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    - apiToken: '*************************************************************************1234'
      channelName: ilya-test-channel
      delayMin: 0
      intervalMin: 60
      typeName: SLACK
    threshold: {}
  - enabled: true
    eventTypeName: CLUSTER_MONGOS_IS_MISSING
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 15
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: CONNECTIONS_PERCENT
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "80.000000"
      units: RAW
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: DISK_PARTITION_SPACE_USED_DATA
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "90.000000"
      units: RAW
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: QUERY_TARGETING_SCANNED_OBJECTS_PER_RETURNED
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "1000.000000"
      units: RAW
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: CREDIT_CARD_ABOUT_TO_EXPIRE
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 1440
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: NORMALIZED_SYSTEM_CPU_USER
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "95.000000"
      units: RAW
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: HOST_HAS_INDEX_SUGGESTIONS
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 10
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: HOST_MONGOT_CRASHING_OOM
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_SERVERLESS_METRIC_THRESHOLD
    metricThreshold:
      metricName: SERVERLESS_CONNECTIONS_PERCENT
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "80.000000"
      units: RAW
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_SERVERLESS_METRIC_THRESHOLD
    metricThreshold:
      metricName: SERVERLESS_DATA_SIZE_TOTAL
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "0.750000"
      units: TERABYTES
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: HOST_NOT_ENOUGH_DISK_SPACE
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: JOINED_GROUP
    metricThreshold:
      threshold: ""
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_SERVERLESS_METRIC_THRESHOLD
    metricThreshold:
      metricName: SERVERLESS_TOTAL_READ_UNITS
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "0.250000"
      units: MILLION_RPU
    notifications:
    - delayMin: 30
      emailEnabled: true
      intervalMin: 720
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_SERVERLESS_METRIC_THRESHOLD
    metricThreshold:
      metricName: SERVERLESS_TOTAL_READ_UNITS
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "1.000000"
      units: MILLION_RPU
    notifications:
    - delayMin: 5
      emailEnabled: true
      intervalMin: 120
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  - enabled: true
    eventTypeName: OUTSIDE_METRIC_THRESHOLD
    metricThreshold:
      metricName: SEARCH_MAX_NUMBER_OF_LUCENE_DOCS
      mode: AVERAGE
      operator: GREATER_THAN
      threshold: "1.000000"
      units: BILLION
    notifications:
    - delayMin: 0
      emailEnabled: true
      intervalMin: 60
      roles:
      - GROUP_OWNER
      smsEnabled: false
      typeName: GROUP
    threshold: {}
  auditing:
    auditAuthorizationSuccess: false
    enabled: false
  connectionSecretRef:
    name: ""
  encryptionAtRest:
    awsKms:
      enabled: false
      valid: false
    azureKeyVault:
      enabled: false
    googleCloudKms:
      enabled: false
  integrations:
  - apiKeyRef:
      name: ""
      namespace: ""
    apiTokenRef:
      name: 61d6f7c953bba44e086a003f-integration-slack
      namespace: atlas
    licenseKeyRef:
      name: ""
      namespace: ""
    passwordRef:
      name: ""
      namespace: ""
    readTokenRef:
      name: ""
      namespace: ""
    routingKeyRef:
      name: ""
      namespace: ""
    secretRef:
      name: ""
      namespace: ""
    serviceKeyRef:
      name: ""
      namespace: ""
    teamName: MySlackTeam
    type: SLACK
    writeTokenRef:
      name: ""
      namespace: ""
  maintenanceWindow: {}
  name: POC_PROJECT
  projectIpAccessList:
  - cidrBlock: 0.0.0.0/0
    comment: temporary
  settings:
    isCollectDatabaseSpecificsStatisticsEnabled: true
    isDataExplorerEnabled: true
    isPerformanceAdvisorEnabled: true
    isRealtimePerformancePanelEnabled: true
    isSchemaAdvisorEnabled: true
status:
  conditions: []
---
apiVersion: v1
data:
  password: KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKjEyMzQ=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    atlas.mongodb.com/type: credentials
  name: 61d6f7c953bba44e086a003f-integration-slack
  namespace: atlas
```

</details>
