### ISSUE TITLE
Unexpected error when reconciling AtlasTeam resources

### ISSUE THREAD

**Issue by jessebye** [mongodb/mongodb-atlas-kubernetes#994]
**What did you do to encounter the bug?**

Create an `AtlasTeam` resource like this:

```
apiVersion: atlas.mongodb.com/v1
kind: AtlasTeam
metadata:
  name: platform-team
  namespace: atlas-operator
spec:
  name: platform-team
  usernames:
  - ab******@riskalyze.com
  - am******@riskalyze.com
```

**What did you expect?**

The team should be created in Atlas.

**What happened instead?**

The team wasn't created, and the operator throws an error:

```
{"level":"INFO","time":"2023-06-14T20:44:54.193Z","msg":"-> Starting AtlasTeam reconciliation","atlasteam":"atlas-operator/platform-team","spec":{"name":"platform-team","usernames":["ab******@riskalyze.com","am********@riskalyze.com"]}}
{"level":"WARN","time":"2023-06-14T20:44:54.317Z","msg":"failed to ensure team state {platform-team [a********@riskalyze.com a**********@riskalyze.com]}: POST https://cloud.mongodb.com/api/atlas/v1.0/orgs/[redacted]/teams: 500 (request \"UNEXPECTED_ERROR\") Unexpected error.","atlasteam":"atlas-operator/platform-team"}
{"level":"INFO","time":"2023-06-14T20:44:54.317Z","msg":"Status update","atlasteam":"atlas-operator/platform-team","lastCondition":{"type":"Ready","status":"False","lastTransitionTime":null,"reason":"TeamNotCreatedInAtlas","message":"POST https://cloud.mongodb.com/api/atlas/v1.0/orgs/[redacted]/teams: 500 (request \"UNEXPECTED_ERROR\") Unexpected error."}}
```

**Screenshots**
n/a

**Operator Information**
 - version 1.7.3

**Kubernetes Cluster Information**
 - EKS
 - 1.24
 - ECR

**Additional context**
Also tested with operator 1.7.1, same issue.
